server:
  port: 8080

spring:
  datasource:
    username: root
    password: root@1234
    url: jdbc:mysql://124.223.51.207:3306/springboot?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.hua.restfulstarter.domain.entity

#showSql
logging:
  level:
    com.hua.restfulstarter.domain.mapper: debug
#  file:
#    name: ./logs/app.log #日志存放的文件
#  logback:
#    rollingpolicy:
#      max-file-size: 10MB
#      max-history: 100
