server:
  port: 8080

spring:
  datasource:
    username: root
    password: root1234
    url: jdbc:mysql://9.134.166.254:3306/springboot?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.hua.restfulstarter.domain.entity

#showSql
logging:
  level:
    com.hua.restfulstarter.domain.mapper: debug
